export interface InterviewQuestion {
  question: string;
  answer: string;
}

export const interviewQuestions: Record<string, InterviewQuestion[]> = {
  helpdesk: [
    {
      question: "A user reports their computer won't turn on at all. Walk me through your troubleshooting steps from the most basic to advanced.",
      answer: "I'd start with the fundamentals: verify the power cable is securely connected to both the computer and outlet, test the outlet with another device, check if the power strip is turned on and functioning. Next, I'd look for LED indicators on the motherboard or power supply, listen for fan noise or beep codes, and try a different power cable. If still no response, I'd reseat the RAM and remove all unnecessary peripherals. For desktop systems, I'd test with a known good power supply. If these fail, it could indicate motherboard or CPU failure requiring component replacement. Throughout this process, I'd document each step and finding in the ticket system."
    },
    {
      question: "Explain the boot process of a Windows computer and where issues commonly occur.",
      answer: "The boot process begins with POST (Power-On Self Test) where BIOS/UEFI checks hardware components. Then it locates the boot device and loads the bootloader (Windows Boot Manager), which reads the BCD (Boot Configuration Data) and loads winload.exe. This starts the kernel, loads drivers, and initializes Windows services before presenting the login screen. Common failure points include: POST failures (hardware issues, beep codes), boot device not found (failed hard drive, incorrect boot order), corrupted bootloader (fixable with bootrec commands), BCD corruption (repairable with bcdedit), driver conflicts causing blue screens during loading, and corrupted system files preventing Windows from starting. Each stage has specific troubleshooting approaches."
    },
    {
      question: "A user's laptop is overheating and shutting down randomly. What are your diagnostic steps and potential solutions?",
      answer: "First, I'd check for obvious airflow obstructions and ensure vents aren't blocked by dust or debris. I'd use compressed air to clean the vents and fan exhausts carefully. Then I'd monitor temperatures using HWMonitor or Core Temp to identify if CPU or GPU is overheating. I'd check Task Manager for processes consuming high CPU, potentially indicating malware or runaway processes. Next steps include: updating BIOS and chipset drivers, checking power settings aren't set to maximum performance unnecessarily, verifying the laptop is on a hard, flat surface for proper ventilation, and potentially replacing thermal paste if the laptop is older. If under warranty, I'd coordinate hardware service for internal cleaning or fan replacement."
    },
    {
      question: "How would you assist a user experiencing intermittent wireless connectivity issues?",
      answer: "I'd start by gathering information: frequency of disconnections, specific times or locations, and whether other devices have issues. First, I'd update the wireless adapter driver and reset TCP/IP stack using netsh commands. I'd check for interference by changing the router channel (especially from crowded 2.4GHz channels), ensure power saving isn't disabled for the wireless adapter, and verify Windows isn't turning off the device to save power. I'd also check signal strength and consider relocating closer to the access point or adding a repeater. Other steps include: checking for VPN software conflicts, disabling IPv6 if not needed, reviewing event logs for specific errors, and potentially replacing the wireless card if hardware failure is suspected. Documentation of when issues occur helps identify patterns."
    },
    {
      question: "Describe your process for removing malware from an infected system while preserving user data.",
      answer: "First, I'd isolate the system from the network to prevent spread. I'd boot into Safe Mode with Networking to limit malware activity. My removal process includes: running Windows Defender Offline scan, using Malwarebytes in Safe Mode, checking with additional tools like ESET Online Scanner or Hitman Pro for second opinions. I'd review startup items, scheduled tasks, and browser extensions for suspicious entries. Important steps include: checking hosts file for redirects, clearing temporary files and browser caches, resetting browser settings to defaults, and verifying system files with SFC and DISM. After cleaning, I'd ensure Windows and antivirus are fully updated, create a restore point, and educate the user on safe browsing practices. If infection is severe, I'd backup user data and perform a clean Windows installation."
    },
    {
      question: "A printer is installed but won't print. What's your systematic approach to resolve this?",
      answer: "I'd start with basic connectivity: verify the printer is powered on, check USB or network cable connections, and confirm the printer shows as online in Devices and Printers. Next, I'd clear the print spooler by stopping the service, deleting files from C:\\Windows\\System32\\spool\\PRINTERS, and restarting the service. I'd then check for driver issues by removing and reinstalling the printer with the latest drivers from the manufacturer. For network printers, I'd verify IP addressing and ping the printer, check firewall rules aren't blocking printing ports, and ensure the user has permissions to the print queue. Additional steps include: printing a test page directly from the printer, checking for paper jams or low ink/toner warnings, and verifying the correct printer is set as default. For persistent issues, I might recreate the user's Windows profile."
    },
    {
      question: "How do you approach data backup and recovery for a small business environment?",
      answer: "I'd implement a 3-2-1 backup strategy: three copies of data, on two different media types, with one copy offsite. For small businesses, I'd recommend: automated daily backups using Windows Server Backup or third-party software like Veeam, local backups to a NAS device for quick recovery, and cloud backups to services like Azure or AWS for disaster recovery. Important considerations include: encrypting sensitive data, testing restore procedures monthly, documenting what data needs backing up and retention periods, implementing versioning to protect against ransomware, and ensuring backups include system state for full server recovery. I'd create a disaster recovery plan with RTO/RPO objectives, maintain backup logs, and train staff on basic recovery procedures. Regular verification ensures backups are valid when needed."
    },
    {
      question: "Explain how you would secure a Windows workstation for a new employee in a corporate environment.",
      answer: "I'd start with a clean Windows installation from our standard image, ensuring all patches are current. Security measures include: enabling BitLocker full-disk encryption, configuring Windows Firewall with appropriate rules, installing enterprise antivirus with real-time protection, enabling Windows Defender features like SmartScreen and Exploit Guard. Account security involves: creating a standard user account (not admin), enforcing strong password policy via Group Policy, enabling account lockout after failed attempts, and configuring MFA where supported. Additional hardening includes: disabling unnecessary services and features, configuring UAC to always prompt, restricting software installation to approved applications, enabling audit logging for security events, and configuring automatic updates. I'd also brief the user on security best practices including phishing awareness and clean desk policy."
    },
    {
      question: "A department is experiencing slow network performance. How would you diagnose and resolve this issue?",
      answer: "I'd begin by defining 'slow' - whether it's internet access, file transfers, or specific applications. Initial diagnostics include: running speed tests from affected computers, checking switch port statistics for errors or high utilization, using netstat to identify unusual connections, and monitoring bandwidth usage by device. I'd verify physical infrastructure: checking for damaged cables, ensuring gigabit negotiation on connections, and confirming switches aren't overloaded. Network analysis involves: using Wireshark to identify broadcast storms or excessive traffic, checking for malware performing network scans, verifying DHCP isn't exhausted, and ensuring DNS responses are timely. Solutions might include: implementing VLANs to segment traffic, enabling QoS for critical applications, updating switch firmware, replacing aging network equipment, or increasing internet bandwidth. Documentation helps identify patterns and justify infrastructure upgrades."
    },
    {
      question: "How would you plan and execute a Windows 10 to Windows 11 migration for 50 users?",
      answer: "I'd start with a comprehensive assessment: running PC Health Check on all machines to verify TPM 2.0 and Secure Boot compatibility, identifying incompatible hardware needing replacement, and testing all business-critical applications for Windows 11 compatibility. Planning phase includes: creating a phased rollout schedule starting with IT and power users, preparing a standard Windows 11 image with all required software, documenting known issues and workarounds, and creating user training materials for UI changes. Execution involves: backing up user data before migration, using SCCM or Intune for deployment, scheduling migrations during off-hours to minimize disruption, and providing hands-on support during the first week. Post-migration: monitoring for issues via help desk tickets, gathering user feedback for process improvement, updating documentation and knowledge base, and planning hardware refresh for incompatible devices. Success requires clear communication and setting realistic expectations."
    }
  ]
};